apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-db-credential
data:
  {{ if ne .Values.awsBackup.secretAccessKey "nothing" }}
  backup-aws-secret: {{.Values.awsBackup.secretAccessKey | b64enc}}
  {{ end }}
  password: {{.Values.db.password | b64enc}}