apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
data:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.username }}
  {{ if ne .Values.awsBackup.secretAccessKey "nothing" }}
  backup-aws-accesskey: {{ .Values.awsBackup.accessKeyId }}
  {{ end }}

