---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-pgpool
  labels:
    name: {{.Release.Name}}-pgpool
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    name: {{.Release.Name}}-pgpool
    app: pgpool