---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-pgread
  labels:
    name: {{.Release.Name}}-pgread
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
    tier: replica