---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-pgwrite
  labels:
    name: {{.Release.Name}}-pgwrite
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
    tier: primary
