---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-postgres-primary-pvc
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    name: {{.Release.Name}}-postgres-primary-pvc
    app: postgres
    tier: primary
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: {{.Values.storage.class}}
  resources:
    requests:
      storage: {{.Values.storage.size}}
