apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-postgres-primary
data:
  makereplica.sh: |+
    #!/bin/bash

    trust="host replication all 0.0.0.0/0 trust"
    echo "$trust" >> /data/pg/pg_hba.conf
    echo "created $trust"